name: Monitoreo vuelos baratos

on:
  schedule:
    # Horarios estratégicos (hora UTC)
    - cron: "0 12 * * 2"  # Martes 9:00 AR
    - cron: "0 12 * * 3"  # Miércoles 9:00 AR
    - cron: "0 15 * * 0"  # Domingo 12:00 AR
    - cron: "0 15 * * *"  # Todos los días 12:00 AR
    - cron: "0 3 * * *"   # Todos los días 00:00 AR
    # Ejecución cada 3 horas
    - cron: "0 0/3 * * *"
  workflow_dispatch:

jobs:
  check-deals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python app.py
