name: Monitoreo vuelos baratos

on:
  schedule:
    # Horarios estratégicos (hora UTC)
    - cron: "0 12 * * 2"  # Martes 9:00 AR
    - cron: "0 12 * * 3"  # Miércoles 9:00 AR
    - cron: "0 15 * * 0"  # Domingo 12:00 AR
    # Ejecución cada 7 horas
    - cron: "0 0/7 * * *"
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CHROME_PATH: /usr/bin/google-chrome
        run: |
          export PATH=$PATH:/usr/bin
          python app.py
